In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
dependent=dataset[["charges"]]

In [ ]:
#for this task we have disables this section
#split into training set and test test
#from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [ ]:
#Standardization - No

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid= {'criterion':['squared_error','absolute_error'], 'max_features':[1.0,'sqrt', 'log2'],'n_estimators':[10,100]}

grid= GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

#fitting model

grid.fit(independent,dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [1.0, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
# print best parameter after tuning
# print (grid.best_params_)

re=grid.cv_results_

print("The R_score value for best parameter {}:" .format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.234954,0.014499,0.014648,0.003731,squared_error,1.0,10,"{'criterion': 'squared_error', 'max_features':...",0.841375,0.758798,0.846064,0.810815,0.836772,0.818765,0.032373,8
1,2.165810,0.008523,0.058965,0.005642,squared_error,1.0,100,"{'criterion': 'squared_error', 'max_features':...",0.849147,0.772877,0.859964,0.817969,0.835231,0.827038,0.030515,5
2,0.162321,0.009280,0.016070,0.008760,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844997,0.741711,0.853024,0.818008,0.820649,0.815678,0.039384,9
3,1.419974,0.011677,0.049625,0.005231,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859879,0.779635,0.858848,0.828606,0.842042,0.833802,0.029449,2
4,0.150162,0.003914,0.012989,0.004160,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.838125,0.752579,0.835053,0.815452,0.830939,0.814430,0.031893,10
5,1.432491,0.005340,0.053713,0.006101,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859997,0.780780,0.862293,0.826664,0.844571,0.834861,0.029901,1
6,0.667637,0.003167,0.019075,0.003930,absolute_error,1.0,10,"{'criterion': 'absolute_error', 'max_features'...",0.835809,0.744250,0.823365,0.825694,0.828988,0.811621,0.033946,12
7,6.013826,0.039376,0.030467,0.004732,absolute_error,1.0,100,"{'criterion': 'absolute_error', 'max_features'...",0.840442,0.767041,0.858398,0.821875,0.834611,0.824473,0.031029,6
8,0.375975,0.009949,0.012756,0.007091,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.851282,0.757573,0.845019,0.815796,0.838016,0.821537,0.034153,7
9,3.707607,0.033600,0.046898,0.005905,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856868,0.781213,0.860334,0.827763,0.842245,0.833685,0.028668,3
10,0.382694,0.018501,0.011139,0.007927,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.835966,0.763825,0.833097,0.819735,0.809466,0.812418,0.026098,11
11,3.024290,0.413449,0.037424,0.004287,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857449,0.778420,0.859348,0.826588,0.839969,0.832355,0.029525,4

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:43
BMI:21
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}". format(Future_Prediction))

Future_Prediction=[8697.8205888]

C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(